FROM python:3.12-slim

WORKDIR /usr/src/app

COPY . .

RUN pip install --no-cache-dir fastapi uvicorn scikit-learn pandas matplotlib

CMD ["uvicorn", "main:app", "--reload", "--host=0.0.0.0", "--port=8000"]